# Generated by Django 2.1.5 on 2019-05-08 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
